# Python Intro 🐍
Este ejercicio tiene como objetivo practicar algunas nociones básicas de Python

##  📕 Operaciones con Strings (str)

Dividir el string dado según los espacios, obteniendo como resultado una lista de las palabras

In [2]:
s = "The universe doesn't allow perfection"
print(s.split())

['The', 'universe', "doesn't", 'allow', 'perfection']


Dado el siguiente texto construya un programa que cuente los caracteres sin contar los espacios:

In [4]:
s = "El pasado puede doler, pero tal como yo lo veo, puedes huir o aprender de él"
print( len(s) - (s.count(" ")))



61


Dado el siguiente texto, remplazar la palbra "apple" por "banana"

In [5]:
s = "If you wish to make an apple pie from scratch, you must first invent the universe"
new_s = s.replace( "apple", "banana")
print(new_s)



If you wish to make an banana pie from scratch, you must first invent the universe


Usar .format() para imprimir el siguiente string:
- The diameter of Earth is 12742 kilometers

In [10]:
planet = "Earth"
diameter = 12742

new_text = "The diameter of {planet} is {diameter}"
print(new_text.format(planet = "Earth", diameter = 12742)) 

The diameter of Earth is 12742


## 🍕 Operaciones con Listas

Dada la siguiente lista, obtener los primeros 3 elementos en una lista disferente (no modificar la lista original)

In [7]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list[:3])

Dada la siguiente lista, obtener los últimos 3 elementos en una lista diferente (no modificar la lista original)

In [8]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list[3:10])

Dada la siguiente lista, obtener solo los números pares

In [22]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for num in lst:
    if num %2 == 0:
        print(num, end=",")


0,2,4,6,8,10,

Dada la siguiente lista, revertir la lista

In [26]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for num in reversed(lst):
    print(num, end=", ")






10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 

Ordenar la siguiente lista de menor a mayor

In [29]:
lst = [4, 1, 6, 12, 3, 2, 1, 7, 1, 0, 14]
lst.sort()
print(lst)
#sort es un método para listas que permite ordenar las mismas.


[0, 1, 1, 1, 2, 3, 4, 6, 7, 12, 14]


Dada la siguiente lista, seleccionar e imprimir la palabra "Hello"

In [53]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2][0])


hello


(Dificultad: medianamente complicado) Ordenar la siguiente lista de diccionarios de mayor a menor y de menor a mayor según el valor de 'age'

In [44]:
nombres_apellidos = [
    {
        "name": "A",
        "age": 12
    },
        {
        "name": "B",
        "age": 22
    },
        {
        "name": "C",
        "age": 2
    },
        {
        "name": "D",
        "age": 4
    },
        {
        "name": "E",
        "age": 42
    },
]

sort_nombres_apellidos = sorted(nombres_apellidos, key=lambda x: x["age"])
print(sort_nombres_apellidos)

rev_nombres_apellidos = sort_nombres_apellidos

for num in reversed(rev_nombres_apellidos):
    print(num, end=", ")

#o tal vez así...  rev_nombres_apellidos =sorted(nombres_apellidos, key=lambda x: x["age"], reversed= True)



[{'name': 'C', 'age': 2}, {'name': 'D', 'age': 4}, {'name': 'A', 'age': 12}, {'name': 'B', 'age': 22}, {'name': 'E', 'age': 42}]
{'name': 'E', 'age': 42}, {'name': 'B', 'age': 22}, {'name': 'A', 'age': 12}, {'name': 'D', 'age': 4}, {'name': 'C', 'age': 2}, 

## 🔥 Funciones
***Principalmente existen 2 formas de crear funciones en python***

In [4]:
#1. def
def function_name_1 (a, b, c):
    #some logic
    return 'Lo que se va a retornar en esta función'

#2. lambda -> muy utilizada para pasarla como argumento dentro de otra función
function_name_2 = lambda a, b, c: 'luego de los puntos va lo que se retorna'

Crear una función que reciba de entrada un correo electrónico en formato string, y retorne el dominio (lo que va desúes de @)
- Entrada: user@domain.com
- Salida esperada: domain.com

In [31]:
mail_entry = "carlitos@hotmail.com"


def mail_user(mail_entry ):
    return mail_entry.split('@')[1]

result = mail_user (mail_entry)
print(result)

hotmail.com


Usar la expresión lambda para filtrar las palabras que no inicien en s de la siguiente lista

In [20]:
words = ['soup','dog','salad','cat','great']

filtered_words= list(filter( lambda word: not word.startswith("s"), words))
##List para convertir el resultado en una lista...
print(filtered_words)


['dog', 'cat', 'great']


Crear una función que reciba 2 parámetros, el primero un frase, y el segundo una palabra (ambos son de tipo string), esta función recisará si la palabra (segundo parámetro) se enceuntra en la frase (primer parámetro), slo retornará True o False según el caso.

In [29]:
phrase= "BlackPink in your area" 
word = "peace"
def parameter_verification (phrase, word):
    return word in phrase

result = parameter_verification (phrase, word)
print(result)

False


Cree una función básica que devuelva True si la palabra 'dog' está contenida en el string dado

In [27]:
s = "Is there a dog here?"

def function_count (s):
    return 'dog' in s.split()

dog_counted = function_count (s)
print(dog_counted)

True


Cree una función que cuente el número de veces que aparece la palabra "dog" en el string dado

In [40]:
s = "This dog runs faster than the other dog dude!"

def function_count (s):
    return(s.count("dog"))

dog_counted = function_count (s)
print(f'La palabra dog se repite {dog_counted} veces')
   



#print(s.count(" dog"))

La palabra dog se repite 2 veces


## 🍎 Numpy básico
La documentación oficial de numpy esta aquí: <a href="https://numpy.org/doc/stable/reference/index.html#reference">Numpy reference</a>

Importa numpy como np

In [ ]:
import numpy as np

Crea un arreglo de 10 ceros

In [53]:
import numpy as np
array_zeros = np.zeros(10)

print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crea un arreglo de 10 unos

In [55]:
import numpy as np
array_ones = np.ones(10)

print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Crea un arreglo de 10 cincos

In [56]:
import numpy as np
array_four = np.ones(10) * 4

print(array_four)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]


Crea un areglo de enteros (int) de 10 a 50

In [6]:
new_array = np.arange(10, 51, 2)
print(new_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Crea una matrix de 3x3 con los valores de 0 a 8
-> Revisar método ***reshape***

In [2]:
import numpy as np
array_a = np.arange(9)
print(array_a)

array_b = array_a.reshape(3, 3)
print (array_b)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Crea un arreglo de tamaño 20 lleno de valores aleatorios entre 10 y 100

In [1]:
import numpy as np
a = np.random.randint(10, 51, size=20)
print(a)

[37 12 48 23 30 22 14 32 21 18 32 29 32 29 47 39 42 20 30 29]


## 🎋 Pandas básico
La documentación oficial de pandas esta aquí: <a href="https://pandas.pydata.org/docs/">Pandas reference</a>

Importa pandas como ***pd***

In [33]:
import pandas as pd

Leer Salaries.csv como un dataframe y llamarlo sal

In [34]:
import pandas as pd

Sal= pd.read_csv('Salaries.csv')
print(Sal)

            Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148

Revisar el head del dataframe (usar el métdodo head())

In [37]:
Sal= pd.read_csv('Salaries.csv')
print(Sal.head())

   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

¿Cual es el BasePay promedio?

In [46]:
import pandas as pd
sal= pd.read_csv('Salaries.csv')
print(Sal.head())

basepay_promedium =  sal['BasePay'].mean()
print('f el promedio de BasePlay es {basepay_promedium}')

   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

¿Cuál es la cantidad más alta de OvertimePay en el conjunto de datos?

In [47]:
sal= pd.read_csv('Salaries.csv')
print(Sal.head())

Overtimepay_highamount =  sal['OvertimePay'].max()
print('f la cantidad más alta de OverTimePlay es {Overtimepay_highamount}')

   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

¿Cuál es el cargo de JOSEPH DRISCOLL? Nota: use mayúsculas, de lo contrario, puede obtener una respuesta que no coincida (también hay un Joseph Driscoll en minúsculas)

In [52]:
Sal= pd.read_csv('Salaries.csv')
print(Sal)

charge_worker = sal.loc['JOSEPH DRISCOLL', 'JobTitle']
print(f'El cargo de JOSEPH DRISCOLL es {charge_worker[0] if not charge_worker.empty else "No se logró encontrar" }')



   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

KeyError: 'JOSEPH DRISCOLL'

¿Cuál es el nombre de la persona mejor pagada (incluidos los beneficios)?

In [59]:
Sal= pd.read_csv('Salaries.csv')
print(Sal)

best_pay = sal.loc[sal['TotalPay'].idxmax(), 'EmployeeName']
print(best_pay)

            Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148

¿Cuántos títulos de trabajo únicos hay?

In [60]:
Sal= pd.read_csv('Salaries.csv')
print(Sal)

unique_jobs = sal ['JobTitle'].unique()
print(f'Estos son los trabajos unicos: {unique_jobs}')

            Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148

## 🍎 Numpy básico
la documentación oficial de numpy esta aquí: <a href="https://numpy.org/doc/stable/reference/index.html#reference">Numpy reference</a>

##  ✨ Bonus

Usando un API construya un programa que muestre la tasa de conversión entre COP y USD, puede usar: <a href="https://exchangeratesapi.io/">Exchange API</a>
- Para interactuar con APIs pueden importar esta librería: ***requests***, <a href="https://requests.readthedocs.io/en/latest/">Aquí su documentación</a>